POSITION_FILE: str = "position_data.csv"
CONFIDENCE_FILE: str = "confidence_data.csv"

DATA_DIR: str = "data"
IMG_DIR: str = "img"

CONNECTIONS_17: dict = {
    "EYE": ["LEFT_EYE", "RIGHT_EYE"],
    "SHOULDER": ["LEFT_SHOULDER", "RIGHT_SHOULDER"],
    "LEFT_UPPER_ARM": ["LEFT_SHOULDER", "LEFT_ELBOW"],
    "RIGHT_UPPER_ARM": ["RIGHT_SHOULDER", "RIGHT_ELBOW"],
    "LEFT_FOREARM": ["LEFT_ELBOW", "LEFT_WRIST"],
    "RIGHT_FOREARM": ["RIGHT_ELBOW", "RIGHT_WRIST"],
    "HIP": ["LEFT_HIP", "RIGHT_HIP"],
    "LEFT_BODY": ["LEFT_SHOULDER", "LEFT_HIP"],
    "RIGHT_BODY": ["RIGHT_SHOULDER", "RIGHT_HIP"],
    "LEFT_THIGH": ["LEFT_HIP", "LEFT_KNEE"],
    "RIGHT_THIGH": ["RIGHT_HIP", "RIGHT_KNEE"],
    "LEFT_LOWER_LEG": ["LEFT_KNEE", "LEFT_ANKLE"],
    "RIGHT_LOWER_LEG": ["RIGHT_KNEE", "RIGHT_ANKLE"],
}

KEYPOINTS_17: list = [
    "NOSE",
    "LEFT_EYE",
    "RIGHT_EYE",
    "LEFT_EAR",
    "RIGHT_EAR",
    "LEFT_SHOULDER",
    "RIGHT_SHOULDER",
    "LEFT_ELBOW",
    "RIGHT_ELBOW",
    "LEFT_WRIST",
    "RIGHT_WRIST",
    "LEFT_HIP",
    "RIGHT_HIP",
    "LEFT_KNEE",
    "RIGHT_KNEE",
    "LEFT_ANKLE",
    "RIGHT_ANKLE",
]
