POSITION_FILE: str = "position_data.csv"
CONFIDENCE_FILE: str = "confidence_data.csv"

DATA_DIR: str = "data"
IMG_DIR: str = "img"

CONNECTIONS_17: dict = {
    "EYE": ["LEFT_EYE", "RIGHT_EYE"],
    "SHOULDER": ["LEFT_SHOULDER", "RIGHT_SHOULDER"],
    "LEFT_UPPER_ARM": ["LEFT_SHOULDER", "LEFT_ELBOW"],
    "RIGHT_UPPER_ARM": ["RIGHT_SHOULDER", "RIGHT_ELBOW"],
    "LEFT_FOREARM": ["LEFT_ELBOW", "LEFT_WRIST"],
    "RIGHT_FOREARM": ["RIGHT_ELBOW", "RIGHT_WRIST"],
    "HIP": ["LEFT_HIP", "RIGHT_HIP"],
    "LEFT_BODY": ["LEFT_SHOULDER", "LEFT_HIP"],
    "RIGHT_BODY": ["RIGHT_SHOULDER", "RIGHT_HIP"],
    "LEFT_THIGH": ["LEFT_HIP", "LEFT_KNEE"],
    "RIGHT_THIGH": ["RIGHT_HIP", "RIGHT_KNEE"],
    "LEFT_LOWER_LEG": ["LEFT_KNEE", "LEFT_ANKLE"],
    "RIGHT_LOWER_LEG": ["RIGHT_KNEE", "RIGHT_ANKLE"],
}

KEYPOINTS_17: list = [
    "NOSE",
    "LEFT_EYE",
    "RIGHT_EYE",
    "LEFT_EAR",
    "RIGHT_EAR",
    "LEFT_SHOULDER",
    "RIGHT_SHOULDER",
    "LEFT_ELBOW",
    "RIGHT_ELBOW",
    "LEFT_WRIST",
    "RIGHT_WRIST",
    "LEFT_HIP",
    "RIGHT_HIP",
    "LEFT_KNEE",
    "RIGHT_KNEE",
    "LEFT_ANKLE",
    "RIGHT_ANKLE",
]

COCO_CATEGORY: dict = {
    "person": 0,
    "bicycle": 1,
    "car": 2,
    "motorcycle": 3,
    "airplane": 4,
    "bus": 5,
    "train": 6,
    "truck": 7,
    "boat": 8,
    "traffic light": 9,
    "fire hydrant": 10,
    "street sign*": 11,
    "stop sign": 12,
    "parking meter": 13,
    "bench": 14,
    "bird": 15,
    "cat": 16,
    "dog": 17,
    "horse": 18,
    "sheep": 19,
    "cow": 20,
    "elephant": 21,
    "bear": 22,
    "zebra": 23,
    "giraffe": 24,
    "hat*": 25,
    "backpack": 26,
    "umbrella": 27,
    "shoe*": 28,
    "eye glasses*": 29,
    "handbag": 30,
    "tie": 31,
    "suitcase": 32,
    "frisbee": 33,
    "skis": 34,
    "snowboard": 35,
    "sports ball": 36,
    "kite": 37,
    "baseball bat": 38,
    "baseball glove": 39,
    "skateboard": 40,
    "surfboard": 41,
    "tennis racket": 42,
    "bottle": 43,
    "plate*": 44,
    "wine glass": 45,
    "cup": 46,
    "fork": 47,
    "knife": 48,
    "spoon": 49,
    "bowl": 50,
    "banana": 51,
    "apple": 52,
    "sandwich": 53,
    "orange": 54,
    "broccoli": 55,
    "carrot": 56,
    "hot dog": 57,
    "pizza": 58,
    "donut": 59,
    "cake": 60,
    "chair": 61,
    "couch": 62,
    "potted plant": 63,
    "bed": 64,
    "mirror*": 65,
    "dining table": 66,
    "window*": 67,
    "desk*": 68,
    "toilet": 69,
    "door*": 70,
    "tv": 71,
    "laptop": 72,
    "mouse": 73,
    "remote": 74,
    "keyboard": 75,
    "cell phone": 76,
    "microwave": 77,
    "oven": 78,
    "toaster": 79,
    "sink": 80,
    "refrigerator": 81,
    "blender*": 82,
    "book": 83,
    "clock": 84,
    "vase": 85,
    "scissors": 86,
    "teddy bear": 87,
    "hair drier": 88,
    "toothbrush": 89,
    "hair brush*": 90,
}
